apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.deployment.name }}
  labels:
  {{- toYaml .Values.deployment.labels | nindent 4 }}
spec:
  selector:
    matchLabels: 
    {{- toYaml .Values.deploymentd.pod.labels | nindent 6 }}
  template:
    metadata:
      labels:
      {{- with .Values.deployment.pod.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.podAnnotations }}
      annotations:
        {{- with .Values.deployment.podannotations }}
          {{- toYaml . | nindent 8 }}
        {{- end}}
      {{- end }}
    spec:
      {{- if .Values.deployment.serviceAccountEnabled }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }} 
      {{- end }}        
      {{- with .Values.deployment.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.containerName }}
          {{- with .Values.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          image: {{ .Values.deployment.containerImage }} 
          {{- with .Values.deployment.containerPorts }}
          ports:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.deployment.containerReadinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end}}
          {{- with .Values.deployment.containerLivenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          {{- range .Values.deployment.container.envVariables }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- with .Values.deployment.containerResources }}
          resources:
            {{- toYaml . | nindent 10 }}
          {{- end }}
