apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }} 
  selector:
    {{- toYaml .Values.service.selectorLabels | nindent 4 }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }} 
    port: {{ .port }} 
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }} 
  {{- end }}
