apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservices.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.deployment.serviceAccountEnabled }}
      serviceAccountName: {{ include "microservices.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.deployment.podTerminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "microservices.containerName" . }}
          {{- with .Values.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.deployment.containerImage }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy | default "IfNotPresent" }}
          {{- with .Values.deployment.containerPorts }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.containerReadinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.containerLivenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.envVariables }}
          env:
            {{- range . }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.containerResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
